# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

#r_build_args: --no-build-vignettes
#r_check_args: --no-build-vignettes

bioc_packages:
  - DESeq2
  - phyloseq

warnings_are_errors: false

r_github_packages:
  - nick-youngblut/HTSSIP


script:
  - |
    R CMD build --no-build-vignettes .
    travis_wait 20 R CMD check --no-vignettes HTSSIP*tar.gz